### ISSUE TITLE
[Feature request] Strike only on disconnect

### ISSUE THREAD

**Issue by TheMicCraft** [CuukyOfficial/VaroPlugin#89]
If the number of max disconnects is set to 0, the player gets a strike even if he is kicked from the server e.g. due to "Flying is not enabled" or "Timed out". However, **the player should only receive a strike if he leaves the server himself** and not if he is not responsible for the kick or disconnect. I'd be happy if an additional setting could be implemented for this case.

**Comment by Almighty-Satan** [comment]
A beta build containing this feature and the fix from #90 is now available via https://dl.varoplugin.de/4.17.3-beta-1. For changelogs see our Discord (or git logs).

Due to a possible potential for abuse by players, the feature is disabled by default but can be enabled in the `disconnect.yml` file. Punishments for combat log are not affected.
